// src/components/CustomCursor.jsx
import React, { useEffect, useRef } from 'react';
import '../styles/CustomCursor.scss';

const CustomCursor = () => {
  const cursorRef = useRef(null);

  useEffect(() => {
    const moveCursor = (e) => {
      if (cursorRef.current) {
        cursorRef.current.style.transform = `translate3d(${e.clientX}px, ${e.clientY}px, 0)`;
      }
    };
    document.addEventListener('mousemove', moveCursor);
    return () => {
      document.removeEventListener('mousemove', moveCursor);
    };
  }, []);

  return (
    <div className="custom-cursor" ref={cursorRef} />
  );
};

export default CustomCursor;

// src/components/CustomCursor.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import '../styles/CustomCursor.scss';

  let cursorRef;

  function moveCursor(e) {
    if (cursorRef) {
      cursorRef.style.transform = `translate3d(${e.clientX}px, ${e.clientY}px, 0)`;
    }
  }

  onMount(() => {
    document.addEventListener('mousemove', moveCursor);
  });

  onDestroy(() => {
    document.removeEventListener('mousemove', moveCursor);
  });
</script>

<div class="custom-cursor" bind:this={cursorRef}></div>
