// src/components/Navigation.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import '../styles/Navigation.scss';

const Navigation = () => {
  const [activeLink, setActiveLink] = useState('');

  const handleMouseEnter = (link) => {
    setActiveLink(link);
  };

  const handleMouseLeave = () => {
    setActiveLink('');
  };

  return (
    <nav className="cyber-nav">
      <div className="nav-glitch-container">
        {['INSTAGRAM', 'TELEGRAM', 'YOUTUBE', 'CONTACT'].map((link) => (
          <Link
            key={link}
            to={`/${link.toLowerCase()}`}
            className={`nav-link ${activeLink === link ? 'active' : ''}`}
            onMouseEnter={() => handleMouseEnter(link)}
            onMouseLeave={handleMouseLeave}
            data-text={link}
          >
            {link}
            <div className="glitch-effect"></div>
          </Link>
        ))}
      </div>
      <div className="nav-scanner"></div>
    </nav>
  );
};

export default Navigation;

// src/components/Navigation.svelte
<script>
  import { writable } from 'svelte/store';
  import '../styles/Navigation.scss';

  // Liste des liens
  const links = ['INSTAGRAM', 'TELEGRAM', 'YOUTUBE', 'CONTACT'];

  // État local pour le lien actif
  let activeLink = '';

  function handleMouseEnter(link) {
    activeLink = link;
  }

  function handleMouseLeave() {
    activeLink = '';
  }
</script>

<nav class="cyber-nav">
  <div class="nav-glitch-container">
    {#each links as link}
      <a
        href="/{link.toLowerCase()}"
        class="nav-link {activeLink === link ? 'active' : ''}"
        on:mouseenter={() => handleMouseEnter(link)}
        on:mouseleave={handleMouseLeave}
        data-text={link}
      >
        {link}
        <div class="glitch-effect"></div>
      </a>
    {/each}
  </div>
  <div class="nav-scanner"></div>
</nav>
